# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    com.example.uaa: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:registry-config@localhost:8761/eureka/

spring:
  profiles:
    active: dev
    include:
    # Uncomment to activate TLS for the dev profile
    #- tls
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  devtools:
    restart:
      enabled: true
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5433/uaa
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: postgres
    hikari:
      pool-name: Hiraki
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: uaa
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
server:
  port: 9999
# ===================================================================
# App specific properties
# ===================================================================
application:
  key-store:
    name: config/tls/keystore.p12
    password: cesarmanuel20
    alias: uaa
  cache: # Cache configuration
    time-to-live-seconds: 3600
    backup-count: 1
    management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
      enabled: false
      update-interval: 3
      url: http://localhost:8180/hazelcast-mancenter
  security:
    # internal client to request AuthorizationServer
    client-authorization:
      client-id: internal
      client-secret: internal
      # Access Token is valid for 5 mins
      token-validity-in-seconds: 300
      # Refresh Token is valid for 7 days
      token-validity-in-seconds-for-remember-me: 252000
  web-client-configuration:
    # Access Token is valid for 5 mins
    access-token-validity-in-seconds: 300
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
    #change client secret in production, keep in sync with gateway configuration
    client-id: web_app
    secret: changeit
  payment:
      paypal:
        credential:
          client-id: cloud
          client-secret: cloud
        mode: sandbox
        url-cancel: http:localhost:3000/pay/calcel
        url-success: http:localhost:3000/pay/succes
        account:
          identifier: bissines@paypal.com
          owner-first-name: Cesar
          owner-last-name:  Cruzata


