# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    ROOT: INFO
    com.example.uaa: debug
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: http://admin:${application.registry-config.password}@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    add-properties: false
  datasource:
    url: ${DATABASE_URL}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${USERNAME_POSTGRES:postgres}
    password: ${PASSWORD_POSTGRES:postgres}
    hikari:
      pool-name: Hiraki
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      #Hibernate can then execute SQL statements in batches, therefore reducing the number of database network roundtrips
      #between 5 and 30
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      #Hibernate can then prevent in-memory pagination when join fetching a child entity collection
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      #Hibernate entity queries can then make better use of statement caching and fewer entity queries will have to be compiled while varying the number of parameters passed to the in query clause
      hibernate.query.in_clause_parameter_padding: true
      # Configuration to Cache Provider Hazelcast
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: uaa
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  # Mail Properties
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: amazingpeople2018@gmail.com
    password: wpoqshasnfbqmsqt #App password auto-generated
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${PORT:9999}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
# ===================================================================
# App specific properties
# ===================================================================
application:
  key-store:
    name: config/tls/keystore.p12
    password: cesarmanuel20
    alias: uaa
  cache: # Cache configuration
    time-to-live-seconds: 3600
    backup-count: 1
    management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
      enabled: false
      update-interval: 3
      url: http://localhost:8180/hazelcast-mancenter
  security:
    # internal client to request AuthorizationServer
    client-authorization:
      client-id: internal
      client-secret: internal
      # Access Token is valid for 5 mins
      token-validity-in-seconds: 300
      # Refresh Token is valid for 7 days
      token-validity-in-seconds-for-remember-me: 252000
  web-client-configuration:
    # Access Token is valid for 5 mins
    access-token-validity-in-seconds: 300
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
    #change client secret in production, keep in sync with gateway configuration
    client-id: web_app
    secret: changeit
  payment:
      paypal:
        credential:
          client-id: cloud
          client-secret: cloud
        mode: sandbox
        url-cancel: http:localhost:3000/pay/calcel
        url-success: http:localhost:3000/pay/succes
        account:
          identifier: bissines@paypal.com
          owner-first-name: Cesar
          owner-last-name:  Cruzata


