# ===================================================================
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
eureka:
  instance:
    appname: uaa
    instanceId: uaa:${spring.application.instance-id:${random.value}}
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['refresh', 'health', 'info']
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  application:
    name: uaa
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false
    hibernate:
      ddl-auto: update

  messages:
    basename: i18n/messages
server:
  servlet:
    session:
      cookie:
        http-only: true
# ===================================================================
# App specific properties
# ===================================================================
application:
  clientApp:
    name: 'uaaApp'